# TCL File Generated by Component Editor 15.1
# Wed Nov 30 01:24:21 EST 2016
# DO NOT MODIFY


# 
# ov7670_camera "OV7670 Camera" v1.0
#  2016.11.30.01:24:21
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module ov7670_camera
# 
set_module_property DESCRIPTION ""
set_module_property NAME ov7670_camera
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Other
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "OV7670 Camera"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ov7670_st
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ov7670_st.vhd VHDL PATH ../src/OV7670_camera/ov7670_st.vhd TOP_LEVEL_FILE
add_fileset_file i2c_sender.vhd VHDL PATH ../src/OV7670_camera/third_party/i2c_sender.vhd
add_fileset_file ov7670_controller.vhd VHDL PATH ../src/OV7670_camera/third_party/ov7670_controller.vhd
add_fileset_file ov7670_registers.vhd VHDL PATH ../src/OV7670_camera/third_party/ov7670_registers.vhd
add_fileset_file ov7670_capture.vhd VHDL PATH ../src/OV7670_camera/ov7670_capture.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_1
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point clock_1
# 
add_interface clock_1 clock end
set_interface_property clock_1 clockRate 0
set_interface_property clock_1 ENABLED true
set_interface_property clock_1 EXPORT_OF ""
set_interface_property clock_1 PORT_NAME_MAP ""
set_interface_property clock_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_1 clock_clk clk Input 1


# 
# connection point line0_out
# 
add_interface line0_out avalon_streaming start
set_interface_property line0_out associatedClock clock_1
set_interface_property line0_out associatedReset reset
set_interface_property line0_out dataBitsPerSymbol 8
set_interface_property line0_out errorDescriptor ""
set_interface_property line0_out firstSymbolInHighOrderBits true
set_interface_property line0_out maxChannel 0
set_interface_property line0_out readyLatency 0
set_interface_property line0_out ENABLED true
set_interface_property line0_out EXPORT_OF ""
set_interface_property line0_out PORT_NAME_MAP ""
set_interface_property line0_out CMSIS_SVD_VARIABLES ""
set_interface_property line0_out SVD_ADDRESS_GROUP ""

add_interface_port line0_out line0_out_data data Output 8
add_interface_port line0_out line0_out_valid valid Output 1
add_interface_port line0_out line0_out_channel channel Output 2
add_interface_port line0_out line0_out_startofpacket startofpacket Output 1
add_interface_port line0_out line0_out_endofpacket endofpacket Output 1


# 
# connection point ov_sensor
# 
add_interface ov_sensor conduit end
set_interface_property ov_sensor associatedClock clock_1
set_interface_property ov_sensor associatedReset ""
set_interface_property ov_sensor ENABLED true
set_interface_property ov_sensor EXPORT_OF ""
set_interface_property ov_sensor PORT_NAME_MAP ""
set_interface_property ov_sensor CMSIS_SVD_VARIABLES ""
set_interface_property ov_sensor SVD_ADDRESS_GROUP ""

add_interface_port ov_sensor ov_sensor_sioc soic Output 1
add_interface_port ov_sensor ov_sensor_siod soid Bidir 1
add_interface_port ov_sensor ov_sensor_reset reset Output 1
add_interface_port ov_sensor ov_sensor_pwdn pwdn Output 1
add_interface_port ov_sensor ov_sensor_vsync vsync Input 1
add_interface_port ov_sensor ov_sensor_href href Input 1
add_interface_port ov_sensor ov_sensor_pclk pclk Input 1
add_interface_port ov_sensor ov_sensor_xclk xclk Output 1
add_interface_port ov_sensor ov_sensor_data data Input 8


# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock_1
set_interface_property control associatedReset reset
set_interface_property control bitsPerSymbol 8
set_interface_property control bridgedAddressOffset 0
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control maximumPendingWriteTransactions 0
set_interface_property control readLatency 0
set_interface_property control readWaitTime 1
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitStates 1
set_interface_property control writeWaitTime 1
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control control_address address Input 8
add_interface_port control control_read read Input 1
add_interface_port control control_readdata readdata Output 32
add_interface_port control control_write write Input 1
add_interface_port control control_writedata writedata Input 32
add_interface_port control control_waitrequest waitrequest Output 1
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0

