# TCL File Generated by Component Editor 15.1
# Sat Nov 26 13:48:49 EST 2016
# DO NOT MODIFY


# 
# pwm_motor_driver "PWM Motor Driver" v1.0
#  2016.11.26.13:48:49
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module pwm_motor_driver
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwm_motor_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Other
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PWM Motor Driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL motor_driver_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file motor_driver_avalon.vhd VHDL PATH ../src/motor_driver/motor_driver_avalon.vhd TOP_LEVEL_FILE
add_fileset_file pwm.vhd VHDL PATH ../src/motor_driver/thirdparty/pwm.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL motor_driver_avalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file motor_driver_avalon.vhd VHDL PATH ../src/motor_driver/motor_driver_avalon.vhd TOP_LEVEL_FILE
add_fileset_file pwm.vhd VHDL PATH ../src/motor_driver/thirdparty/pwm.vhd


# 
# parameters
# 
add_parameter sys_clk INTEGER 50000000
set_parameter_property sys_clk DEFAULT_VALUE 50000000
set_parameter_property sys_clk DISPLAY_NAME sys_clk
set_parameter_property sys_clk TYPE INTEGER
set_parameter_property sys_clk UNITS None
set_parameter_property sys_clk ALLOWED_RANGES -2147483648:2147483647
set_parameter_property sys_clk HDL_PARAMETER true
add_parameter pwm_freq INTEGER 100000
set_parameter_property pwm_freq DEFAULT_VALUE 100000
set_parameter_property pwm_freq DISPLAY_NAME pwm_freq
set_parameter_property pwm_freq TYPE INTEGER
set_parameter_property pwm_freq UNITS None
set_parameter_property pwm_freq ALLOWED_RANGES -2147483648:2147483647
set_parameter_property pwm_freq HDL_PARAMETER true
add_parameter bits_resolution INTEGER 8
set_parameter_property bits_resolution DEFAULT_VALUE 8
set_parameter_property bits_resolution DISPLAY_NAME bits_resolution
set_parameter_property bits_resolution TYPE INTEGER
set_parameter_property bits_resolution UNITS None
set_parameter_property bits_resolution ALLOWED_RANGES -2147483648:2147483647
set_parameter_property bits_resolution HDL_PARAMETER true
add_parameter phases INTEGER 1
set_parameter_property phases DEFAULT_VALUE 1
set_parameter_property phases DISPLAY_NAME phases
set_parameter_property phases TYPE INTEGER
set_parameter_property phases UNITS None
set_parameter_property phases ALLOWED_RANGES -2147483648:2147483647
set_parameter_property phases HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitStates 1
set_interface_property avs_s0 writeWaitTime 1
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point output_pins
# 
add_interface output_pins conduit end
set_interface_property output_pins associatedClock ""
set_interface_property output_pins associatedReset ""
set_interface_property output_pins ENABLED true
set_interface_property output_pins EXPORT_OF ""
set_interface_property output_pins PORT_NAME_MAP ""
set_interface_property output_pins CMSIS_SVD_VARIABLES ""
set_interface_property output_pins SVD_ADDRESS_GROUP ""

add_interface_port output_pins motor_pin_a pin_a Output 1
add_interface_port output_pins motor_pin_b pin_b Output 1

